const usuarios = [
    { 
        id: 0,
        name: 'Andrés Felipe', 
        lastname: 'Garcia Castro',
        identi: 114485404, 
        RA: 'Administrador',
        state: 'Activo', 
        contrasena: "123",
        phone: 3165303978,
        mail: 'afgarcia@refinal.com',
     },
     { 
        id: 1,
        name: 'Elizabeth', 
        lastname: 'Arboleda',
        identi: 665789080, 
        RA: 'Administrador',
        state: 'Inactivo',
        contrasena: "123", 
        phone: 3165303978,
        mail: 'earboleda@refinal.com',
     },
     { 
        id: 2,
        name: 'Jader', 
        lastname: 'Penagos',
        identi: 665789043, 
        RA: 'Conductor',
        state: 'Activo',
        contrasena: "123", 
        phone: 3175303978,
        mail: 'jpenago@refinal.com',
     },
     { 
        id: 3,
        name: 'Diana', 
        lastname: 'Villa',
        identi: 1122567890, 
        RA: 'Recolector',
        state: 'Activo',
        contrasena: "123", 
        phone: 3005303976,
        mail: 'dvilla@refinal.com',
     },
     { 
        id: 4,
        name: 'Luis Andrés', 
        lastname: 'Murillo',
        identi: 1144198789, 
        RA: 'Administrador',
        state: 'Activo',
        contrasena: "123", 
        phone: 3005303976,
        mail: 'lamurillo@refinal.com',
     },
     { 
        id: 5,
        name: 'Jairo', 
        lastname: 'Gutierrez',
        identi: 44789056, 
        RA: 'Coordinador',
        state: 'Activo',
        contrasena: "123", 
        phone: 3125333977,
        mail: 'jgutierrez@refinal.com',
     },
     { 
        id: 6,
        name: 'Alexandra', 
        lastname: 'Culcha',
        identi: 1144198786, 
        RA: 'Digitador CG-UNO',
        state: 'Inactivo',
        contrasena: "123", 
        phone: 3145439560,
        mail: 'aculcha@refinal.com',
     },
     { 
        id: 7,
        name: 'Valentina', 
        lastname: 'Zapata',
        identi: 72567788, 
        RA: 'Recolector',
        state: 'Activo',
        contrasena: "123", 
        phone: 3157893970,
        mail: 'vzapata@refinal.com',
     },
  ];

  export default usuarios;